server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
      - id: Identity
        uri: http://localhost:9094
        predicates:
        - Path=/auth/**
        filters:
        - AuthenticationFilter
      - id: Transporte
        uri: http://localhost:9091
        predicates:
        - Path=/transporte/**
        filters:
        - AuthenticationFilter
      - id: Molino
        uri: http://localhost:9092
        predicates:
        - Path=/molino/**
        filters:
        - AuthenticationFilter
      - id: SUNAT
        uri: http://localhost:9001
        predicates:
        - Path=/api/sunat/**
        filters:
        - AuthenticationFilter
