server:
  port: 8082

spring:
  cloud:
    gateway:
      default-filters: 
        - name: AuthenticationFilter

      routes:
        - id: Identity
          uri: http://localhost:9094
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 

        - id: Transporte
          uri: http://localhost:9091
          predicates:
            - Path=/transporte/**
          filters:
            - StripPrefix=1 

        - id: Molino
          uri: http://localhost:9092
          predicates:
            - Path=/molino/**
          filters:
            - StripPrefix=1

        - id: SUNAT
          uri: http://localhost:9001
          predicates:
            - Path=/api/sunat/**
          filters:
            - StripPrefix=2 
