server:
  port: 9001

api:
  sunat:
    base-url: https://api.apis.net.pe/v2/sunat
    token: apis-token-11883.WqaDygNAYLfrLIzJ7fxJ07YafF9yv297 # Coloca tu token válido aquí

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # Actualizado a la versión correcta
    url: jdbc:mysql://localhost:3306/bdromero
    username: root
    password: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Usar MySQL8Dialect para versiones modernas
    hibernate:
      ddl-auto: update  # Generación automática de las tablas
      format_sql: true  # Formato legible para las consultas SQL
    show-sql: true  # Mostrar las consultas SQL en la consola
